

easy_admin:
   site_name: DcCollab

   design:
      menu:
         - {route: 'homepage', label: 'Back to website', icon: 'home'}
         - {entity: 'User', label: 'Users', icon: 'user' }
         - {entity: 'Projet', label: 'Projets', icon: 'folder-open' }
         - {entity: 'Competence', label: 'Compétences', icon: 'folder-open' }
         - {entity: 'Ecole', label: 'Ecoles', icon: 'folder-open' }
         - {entity: 'Filiere', label: 'Filieres', icon: 'folder-open' }


   entities:
#     # List the entity class name you want to manage

      User:
         class: App\Entity\User

      Projet:
         class: App\Entity\Projet

      Categorie:
         class: App\Entity\Categorie

      Competence:
         class: App\Entity\Competence

      Ecole:
         class: App\Entity\Ecole

      Filiere:
         class: App\Entity\Filiere





